  snyk-oss:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest
    concurrency:
      group: snyk-oss-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true  # habilita cache de módulos

      - name: Download Go modules
        run: go mod download

      - name: Verify Go modules
        run: go mod verify

      - name: Set up Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk OSS
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=high